name: string-function

on: push

jobs:
  string-function:
    runs-on: ubuntu-latest
    steps:
      - name: startswith git
        if: startsWith('github actions','git')
        run: echo 'git'

      - name: startswith test
        if: startsWith('github actions','test')
        run: echo 'test'

      - name: endswith ions
        if: endsWith('github actions','ions')
        run: echo 'ions'

      - name: endswith test
        if: endsWith('github actions','test')
        run: echo 'test'

      - name: contains act
        if: contains('github actions','act')
        run: echo 'act'

      - name: contains test
        if: contains('github actions','test')
        run: echo 'test'